import * as cdk from 'aws-cdk-lib';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { Construct } from 'constructs';
import * as path from 'path';
import * as fs from 'fs';

import { tagStack } from './config';

export interface WebStackProps extends cdk.StackProps {
  readonly loadBalancer: elbv2.IApplicationLoadBalancer;
  readonly userPoolId: string;
  readonly userPoolClientId: string;
  readonly hostedUiDomain: string;
}

/**
 * CloudFront in front of an S3 bucket for the React app, with `/api/*` routed to
 * the ALB.
 *
 * One distribution rather than a separate API domain: the UI and API become
 * same-origin, so there is no CORS preflight on every call and no third place to
 * configure allowed origins. It also means the browser never learns the ALB's
 * hostname, so the only public entry point is CloudFront.
 */
export class WebStack extends cdk.Stack {
  readonly distribution: cloudfront.Distribution;
  readonly url: string;

  constructor(scope: Construct, id: string, props: WebStackProps) {
    super(scope, id, props);
    tagStack(this, 'web');

    const bucket = new s3.Bucket(this, 'UiBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      // A compiled front-end bundle. Regenerated by every build, so there is
      // nothing here worth retaining.
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    /**
     * Serve the SPA shell for client-side routes, at the edge.
     *
     * A deep link like /documents is not an object in S3. Rather than let it 404 and be
     * rescued by a distribution-wide `errorResponses` rule — which also rewrote genuine
     * API errors into HTML-with-200 — anything without a file extension is rewritten to
     * /index.html here. This function is attached only to the SPA behaviour, so `/api/*`
     * is untouched and its status codes reach the browser intact.
     */
    const rewriteSpaRoutes = new cloudfront.Function(this, 'RewriteSpaRoutes', {
      code: cloudfront.FunctionCode.fromInline(`
function handler(event) {
  var uri = event.request.uri;
  // A dot in the last segment means a real asset (.js, .css, .json, .svg).
  var last = uri.substring(uri.lastIndexOf('/') + 1);
  if (last.indexOf('.') === -1) event.request.uri = '/index.html';
  return event.request;
}
      `),
    });

    // No /api rewrite here, deliberately.
    //
    // `app.py` mounts every router at `prefix="/api"`, so the API already serves the
    // paths the UI asks for. Stripping the prefix turned `/api/tenants/{t}/dashboard`
    // into `/tenants/{t}/dashboard`, which FastAPI does not serve — every tenant
    // endpoint 404'd, the SPA error response returned index.html, and `res.json()`
    // threw, so the UI silently fell back to fixtures. `/api/health` was the only
    // survivor, because app.py happens to define a bare `/health` as well.
    //
    // If a rewrite is ever reintroduced, remove `prefix="/api"` in app.py in the same
    // change: exactly one of the two may own the prefix.

    this.distribution = new cloudfront.Distribution(this, 'Distribution', {
      comment: 'LexGraph',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        functionAssociations: [
          { function: rewriteSpaRoutes, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST },
        ],
      },
      additionalBehaviors: {
        '/api/*': {
          // HTTP to the ALB. Acceptable only because that hop is inside the VPC's
          // public subnets; put ACM on the ALB before this handles real matters.
          origin: new origins.HttpOrigin(props.loadBalancer.loadBalancerDnsName, {
            protocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
            readTimeout: cdk.Duration.seconds(60),
          }),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          // Never cache: every response is tenant-scoped, and a shared cache key
          // across tenants is precisely the leak this system cannot have.
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
        },
      },
      defaultRootObject: 'index.html',
      // No `errorResponses`, deliberately.
      //
      // It cannot be scoped to a behaviour — it applies to the whole distribution,
      // `/api/*` included. Mapping 403/404 to index.html with status 200 meant every API
      // refusal and every API not-found came back as an HTML page with a success status.
      // The UI's `res.json()` then threw, and `fallback()` quietly substituted fixtures,
      // so a broken API looked like a working demo.
      //
      // SPA deep links are handled at the edge instead (`rewriteSpaRoutes`), which
      // rewrites extensionless paths to /index.html so S3 never sees a miss.
      // No minimumProtocolVersion: on the default *.cloudfront.net certificate the
      // security policy is fixed and the setting is silently ignored. It only
      // takes effect once a custom domain and ACM certificate are attached, which
      // is a prerequisite for handling real matters anyway.
    });

    this.url = `https://${this.distribution.distributionDomainName}`;

    this.deployUi(bucket, props);

    new cdk.CfnOutput(this, 'WebUrl', { value: this.url });
    new cdk.CfnOutput(this, 'UiBucketName', { value: bucket.bucketName });
  }

  /**
   * Cognito ids are published as a fetched JSON file rather than baked into the
   * bundle at build time. Otherwise the front-end could not be rebuilt without
   * the CDK outputs to hand, and `web` would have to be redeployed whenever
   * `auth` changed a client id.
   */
  private deployUi(bucket: s3.IBucket, props: WebStackProps): void {
    const uiDir = path.join(__dirname, '../../ui');
    const runtimeConfig = s3deploy.Source.jsonData('runtime-config.json', {
      cognitoUserPoolId: props.userPoolId,
      cognitoClientId: props.userPoolClientId,
      cognitoRegion: this.region,
      cognitoDomain: props.hostedUiDomain,
      apiBaseUrl: '/api',
    });

    // The UI is owned by another agent and may not have a package.json yet.
    // Synthesising a bucket with only runtime-config.json is a working, if empty,
    // deploy; failing synth here would block every other stack.
    const hasBuildableUi = fs.existsSync(path.join(uiDir, 'package.json'));

    new s3deploy.BucketDeployment(this, 'UiDeploy', {
      sources: hasBuildableUi
        ? [
            s3deploy.Source.asset(uiDir, {
              exclude: ['node_modules', 'dist'],
              bundling: {
                image: cdk.DockerImage.fromRegistry('node:20-slim'),
                command: [
                  'bash',
                  '-c',
                  'npm ci --cache /tmp/.npm && npm run build && cp -r dist/* /asset-output/',
                ],
              },
            }),
            runtimeConfig,
          ]
        : [runtimeConfig],
      destinationBucket: bucket,
      distribution: this.distribution,
      distributionPaths: ['/*'],
    });
  }
}
